site_name: Lslightly's Stars
site_url: https://lslightly.github.io/stars
repo_url: https://github.com/Lslightly/stars
theme:
  icon:
    repo: fontawesome/brands/github
    tag:
      Go: fontawesome/brands/golang
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#configuration
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
  # https://github.com/sondregronas/mkdocs-callouts
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
plugins:
  - tags
  - glightbox
  - search
  - callouts
extra:
  generator: true
  tags:
    Go: Go
nav:
  - Home: index.md
  - Details:
    - details/goref.md
    - details/conbon-pprof2csv.md
    - details/coregex.md
